apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java
  replicas: 1
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: anjaliacr.azurecr.io/dockerimage_poc1:15
        ports:
        - containerPort: 8080
---

kind: Service 
apiVersion: v1
metadata:
  name: java-service
spec:
  selector:
    app: java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer



 